version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: TodoList
    environment:
      POSTGRES_DB: ${DATABASE_URLD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5431:5432"
    restart: always